version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/static
    command: gunicorn shivai_temple.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 80
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=shivaidevishivna.in,www.shivaidevishivna.in
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=shivaidevishivna.in,www.shivaidevishivna.in
      - LETSENCRYPT_EMAIL=info@credencesolutions.in

networks:
  default:
    external:
      name: nginx-proxy

volumes: 
  static_volume:
